import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const reportService = {
    async generateWeeklyPDF(data: any) {
        const html = `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1B4332; }
            h1 { color: #1B4332; font-size: 32px; margin-bottom: 5px; }
            .subtitle { color: #FB8C00; font-size: 18px; margin-bottom: 30px; font-weight: bold; }
            .card { background: #f9f9f9; padding: 20px; border-radius: 12px; margin-bottom: 20px; border: 1px solid #e0e0e0; }
            .score { font-size: 48px; font-weight: bold; color: #1B4332; }
            .stat-grid { display: flex; justify-content: space-between; margin-bottom: 30px; }
            .stat-item { text-align: center; flex: 1; }
            .stat-value { font-size: 24px; font-weight: bold; display: block; }
            .stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
            .coach-tip { font-style: italic; color: #444; border-left: 4px solid #7CB342; padding-left: 15px; }
            footer { margin-top: 50px; font-size: 10px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <h1>NutriGyani Health Report</h1>
          <div class="subtitle">Weekly Summary: June 20 - June 26, 2026</div>
          
          <div class="card">
            <div class="stat-label">Average Health Score</div>
            <div class="score">${data.averageScore}/100</div>
          </div>

          <div class="stat-grid">
            <div class="stat-item">
              <span class="stat-value">${data.totalCalories}</span>
              <span class="stat-label">Avg Calories</span>
            </div>
            <div class="stat-item">
              <span class="stat-value">${data.avgProtein}g</span>
              <span class="stat-label">Avg Protein</span>
            </div>
            <div class="stat-item">
              <span class="stat-value">${data.avgCarbs}g</span>
              <span class="stat-label">Avg Carbs</span>
            </div>
          </div>

          <h3>NutriGyani's Personal Advice</h3>
          <div class="coach-tip">
            "${data.coachAdvice}"
          </div>

          <div class="card" style="margin-top: 30px;">
            <h3>Top Recommendations</h3>
            <ul>
              ${data.recommendations.map((r: string) => `<li>${r}</li>`).join('')}
            </ul>
          </div>

          <footer>
            This report was generated by NutriGyani AI. Always consult a professional for medical advice.
          </footer>
        </body>
      </html>
    `;

        try {
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (error) {
            console.error('PDF Generation Error:', error);
            throw error;
        }
    }
};
